remove bin_links.txt

diff --git a/scripts/bin-link-checker b/scripts/bin-link-checker
--- a/scripts/bin-link-checker
+++ b/scripts/bin-link-checker
@@ -6,7 +6,7 @@ caller=$0 cmds_defined readlink ansi256 || exit 1
 
 binlinksfile=${BIN_LINKS_FILE:-~/rams_dot_files/bin_links.txt}
 bindir=~/bin
-[ ! -f "$binlinksfile" ] && echo "file $binlinksfile NOT found!" && exit 1
+[ ! -f "$binlinksfile" ] && echo "file $(ansi256 -f red "$binlinksfile") NOT found!" && exit 1
 
 echo "reading bin links from file $(ansi256 -f yellow $binlinksfile)"
 echo ""
