fixes

diff --git a/scripts/chrome-json-summary b/scripts/chrome-json-summary
--- a/scripts/chrome-json-summary
+++ b/scripts/chrome-json-summary
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-[ ! "$(uname)" = "Darwin" ] && \
-    echo "RLY-ERROR: chrome_json_summary needs applescript, only Darwin os" >&2 && return 1
+[ ! "$(uname)" = "Darwin" ] && echo "RLY-ERROR: chrome_json_summary needs applescript, only Darwin os" >&2 && exit 1
+
 wincount=$(osascript -e 'tell application "Google Chrome" to get number of windows')
 [ "$wincount" -eq 0 ] && echo "zero windows!" && return
 
